name: Build and Push Docker image

on:
  workflow_call:
    inputs:
      pull_branch:
        description: 'pull after checkout (ie, caller commited)'
        required: false
        default: false
        type: boolean

jobs:
  version_extractor:
    runs-on: "ubuntu-24.04-arm"
    outputs:
      runner_version: ${{ steps.extractor.outputs.runner_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull
        if: ${{ inputs.pull_branch }}
        run: git pull

      - name: Extract runner version
        id: extractor
        run: echo "runner_version=$(cat Dockerfile | grep 'ARG RUNNER_VERSION' | cut -d '=' -f 2 | sed -e 's/"//g')" >> $GITHUB_OUTPUT

  build:
    needs: version_extractor
    runs-on: "ubuntu-24.04-arm"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull
        if: ${{ inputs.pull_branch }}
        run: git pull

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ghrape:${{ needs.version_extractor.outputs.runner_version }},ghcr.io/${{ github.repository_owner }}/ghrape:latest
          provenance: false
