name: Build image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-24.04-arm"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ghrape:${{ github.sha }},ghcr.io/${{ github.repository_owner }}/ghrape:LATEST
          provenance: false
