name: Main branch CI/CD

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build-image.yaml'
      - 'Dockerfile'
      - 'start.sh'

jobs:
  build-image:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-image.yaml
